version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "review"
      - "dependencies"
    groups:
      avalonia:
        patterns:
          - "Avalonia*"
      xunit:
        patterns:
          - "xunit*"
  - package-ecosystem: gitsubmodule
    directory: "/"
    schedule:
        interval: "daily"
    labels:
      - "review"
      - "dependencies"
