//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThriveLauncher.Properties {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources_fi {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources_fi() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("ThriveLauncher.Properties.Resources_fi", typeof(Resources_fi).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string SettingsImportOldTitle {
            get {
                return ResourceManager.GetString("SettingsImportOldTitle", resourceCulture);
            }
        }
        
        public static string SettingsImportOldExplanation {
            get {
                return ResourceManager.GetString("SettingsImportOldExplanation", resourceCulture);
            }
        }
        
        public static string PerformImport {
            get {
                return ResourceManager.GetString("PerformImport", resourceCulture);
            }
        }
        
        public static string SkipAction {
            get {
                return ResourceManager.GetString("SkipAction", resourceCulture);
            }
        }
        
        public static string ImportFailedTitle {
            get {
                return ResourceManager.GetString("ImportFailedTitle", resourceCulture);
            }
        }
        
        public static string ImportSucceededTitle {
            get {
                return ResourceManager.GetString("ImportSucceededTitle", resourceCulture);
            }
        }
        
        public static string ImportSucceededMessage {
            get {
                return ResourceManager.GetString("ImportSucceededMessage", resourceCulture);
            }
        }
        
        public static string ImportFailedMessage {
            get {
                return ResourceManager.GetString("ImportFailedMessage", resourceCulture);
            }
        }
    }
}
