//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThriveLauncher.Properties {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("ThriveLauncher.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string SettingsImportOldTitle {
            get {
                return ResourceManager.GetString("SettingsImportOldTitle", resourceCulture);
            }
        }
        
        public static string SettingsImportOldExplanation {
            get {
                return ResourceManager.GetString("SettingsImportOldExplanation", resourceCulture);
            }
        }
        
        public static string SkipAction {
            get {
                return ResourceManager.GetString("SkipAction", resourceCulture);
            }
        }
        
        public static string PerformImport {
            get {
                return ResourceManager.GetString("PerformImport", resourceCulture);
            }
        }
        
        public static string ImportFailedTitle {
            get {
                return ResourceManager.GetString("ImportFailedTitle", resourceCulture);
            }
        }
        
        public static string ImportFailedMessage {
            get {
                return ResourceManager.GetString("ImportFailedMessage", resourceCulture);
            }
        }
        
        public static string ImportSucceededTitle {
            get {
                return ResourceManager.GetString("ImportSucceededTitle", resourceCulture);
            }
        }
        
        public static string ImportSucceededMessage {
            get {
                return ResourceManager.GetString("ImportSucceededMessage", resourceCulture);
            }
        }
        
        public static string LauncherSelectedLanguage {
            get {
                return ResourceManager.GetString("LauncherSelectedLanguage", resourceCulture);
            }
        }
        
        public static string LinksButton {
            get {
                return ResourceManager.GetString("LinksButton", resourceCulture);
            }
        }
        
        public static string PlayButton {
            get {
                return ResourceManager.GetString("PlayButton", resourceCulture);
            }
        }
        
        public static string ConnectToDevCenterPrompt {
            get {
                return ResourceManager.GetString("ConnectToDevCenterPrompt", resourceCulture);
            }
        }
        
        public static string ConnectedDeveloperGreeting {
            get {
                return ResourceManager.GetString("ConnectedDeveloperGreeting", resourceCulture);
            }
        }
        
        public static string ConnectedSupporterGreeting {
            get {
                return ResourceManager.GetString("ConnectedSupporterGreeting", resourceCulture);
            }
        }
        
        public static string DevelopmentFeedTitle {
            get {
                return ResourceManager.GetString("DevelopmentFeedTitle", resourceCulture);
            }
        }
        
        public static string WebContentIsDisabled {
            get {
                return ResourceManager.GetString("WebContentIsDisabled", resourceCulture);
            }
        }
        
        public static string NewsFeedTitle {
            get {
                return ResourceManager.GetString("NewsFeedTitle", resourceCulture);
            }
        }
        
        public static string LinksPopupTitle {
            get {
                return ResourceManager.GetString("LinksPopupTitle", resourceCulture);
            }
        }
        
        public static string ExternalLinkMainWebsite {
            get {
                return ResourceManager.GetString("ExternalLinkMainWebsite", resourceCulture);
            }
        }
        
        public static string ExternalLinkDevelopmentForums {
            get {
                return ResourceManager.GetString("ExternalLinkDevelopmentForums", resourceCulture);
            }
        }
        
        public static string ExternalLinkCommunityForums {
            get {
                return ResourceManager.GetString("ExternalLinkCommunityForums", resourceCulture);
            }
        }
        
        public static string ExternalLinkDeveloperWiki {
            get {
                return ResourceManager.GetString("ExternalLinkDeveloperWiki", resourceCulture);
            }
        }
        
        public static string ExternalLinkPatreon {
            get {
                return ResourceManager.GetString("ExternalLinkPatreon", resourceCulture);
            }
        }
        
        public static string ExternalLinkDonate {
            get {
                return ResourceManager.GetString("ExternalLinkDonate", resourceCulture);
            }
        }
        
        public static string ExternalLinkThriveDevCenter {
            get {
                return ResourceManager.GetString("ExternalLinkThriveDevCenter", resourceCulture);
            }
        }
        
        public static string ExternalLinkThriveSteam {
            get {
                return ResourceManager.GetString("ExternalLinkThriveSteam", resourceCulture);
            }
        }
        
        public static string ExternalLinkThriveItch {
            get {
                return ResourceManager.GetString("ExternalLinkThriveItch", resourceCulture);
            }
        }
        
        public static string ExternalLinkThriveGithub {
            get {
                return ResourceManager.GetString("ExternalLinkThriveGithub", resourceCulture);
            }
        }
        
        public static string ExternalLinkLauncherGithub {
            get {
                return ResourceManager.GetString("ExternalLinkLauncherGithub", resourceCulture);
            }
        }
        
        public static string ExternalLinkFanWiki {
            get {
                return ResourceManager.GetString("ExternalLinkFanWiki", resourceCulture);
            }
        }
        
        public static string ExternalLinkDiscordServer {
            get {
                return ResourceManager.GetString("ExternalLinkDiscordServer", resourceCulture);
            }
        }
        
        public static string ExternalLinkSubreddit {
            get {
                return ResourceManager.GetString("ExternalLinkSubreddit", resourceCulture);
            }
        }
        
        public static string ExternalLinkYouTubeChannel {
            get {
                return ResourceManager.GetString("ExternalLinkYouTubeChannel", resourceCulture);
            }
        }
        
        public static string ExternalLinkTwitterFeed {
            get {
                return ResourceManager.GetString("ExternalLinkTwitterFeed", resourceCulture);
            }
        }
        
        public static string ExternalLinkFacebookPage {
            get {
                return ResourceManager.GetString("ExternalLinkFacebookPage", resourceCulture);
            }
        }
        
        public static string ThriveOptions {
            get {
                return ResourceManager.GetString("ThriveOptions", resourceCulture);
            }
        }
        
        public static string LauncherOptions {
            get {
                return ResourceManager.GetString("LauncherOptions", resourceCulture);
            }
        }
        
        public static string InstalledVersions {
            get {
                return ResourceManager.GetString("InstalledVersions", resourceCulture);
            }
        }
        
        public static string CacheConfigurationTab {
            get {
                return ResourceManager.GetString("CacheConfigurationTab", resourceCulture);
            }
        }
        
        public static string LaunchOptionsTitle {
            get {
                return ResourceManager.GetString("LaunchOptionsTitle", resourceCulture);
            }
        }
        
        public static string LaunchOptionDisableVideos {
            get {
                return ResourceManager.GetString("LaunchOptionDisableVideos", resourceCulture);
            }
        }
        
        public static string LaunchOptionForceGLES2 {
            get {
                return ResourceManager.GetString("LaunchOptionForceGLES2", resourceCulture);
            }
        }
        
        public static string LauncherVersionDisplay {
            get {
                return ResourceManager.GetString("LauncherVersionDisplay", resourceCulture);
            }
        }
        
        public static string LauncherOptionWebFeeds {
            get {
                return ResourceManager.GetString("LauncherOptionWebFeeds", resourceCulture);
            }
        }
        
        public static string LauncherOptionHide32Bit {
            get {
                return ResourceManager.GetString("LauncherOptionHide32Bit", resourceCulture);
            }
        }
        
        public static string LauncherOptionHideOnPlay {
            get {
                return ResourceManager.GetString("LauncherOptionHideOnPlay", resourceCulture);
            }
        }
        
        public static string LauncherOptionCloseAfterPlaying {
            get {
                return ResourceManager.GetString("LauncherOptionCloseAfterPlaying", resourceCulture);
            }
        }
        
        public static string LauncherOptionCloseAfterStart {
            get {
                return ResourceManager.GetString("LauncherOptionCloseAfterStart", resourceCulture);
            }
        }
        
        public static string LauncherOptionAllowSeamlessMode {
            get {
                return ResourceManager.GetString("LauncherOptionAllowSeamlessMode", resourceCulture);
            }
        }
        
        public static string LauncherOptionAutoUpdate {
            get {
                return ResourceManager.GetString("LauncherOptionAutoUpdate", resourceCulture);
            }
        }
        
        public static string ResetAllSettings {
            get {
                return ResourceManager.GetString("ResetAllSettings", resourceCulture);
            }
        }
        
        public static string BrowseInstalledFiles {
            get {
                return ResourceManager.GetString("BrowseInstalledFiles", resourceCulture);
            }
        }
        
        public static string SelectInstallLocation {
            get {
                return ResourceManager.GetString("SelectInstallLocation", resourceCulture);
            }
        }
        
        public static string ResetInstallLocationToolTip {
            get {
                return ResourceManager.GetString("ResetInstallLocationToolTip", resourceCulture);
            }
        }
        
        public static string FolderPathDisplay {
            get {
                return ResourceManager.GetString("FolderPathDisplay", resourceCulture);
            }
        }
        
        public static string TemporaryDownloadsPathDisplay {
            get {
                return ResourceManager.GetString("TemporaryDownloadsPathDisplay", resourceCulture);
            }
        }
        
        public static string FolderContentsLabel {
            get {
                return ResourceManager.GetString("FolderContentsLabel", resourceCulture);
            }
        }
        
        public static string FolderIsEmpty {
            get {
                return ResourceManager.GetString("FolderIsEmpty", resourceCulture);
            }
        }
        
        public static string TemporaryFolderNoFilesMoveNotice {
            get {
                return ResourceManager.GetString("TemporaryFolderNoFilesMoveNotice", resourceCulture);
            }
        }
        
        public static string SelectTemporaryFilesLocation {
            get {
                return ResourceManager.GetString("SelectTemporaryFilesLocation", resourceCulture);
            }
        }
        
        public static string ResetTemporaryLocation {
            get {
                return ResourceManager.GetString("ResetTemporaryLocation", resourceCulture);
            }
        }
        
        public static string ClearTemporaryLocation {
            get {
                return ResourceManager.GetString("ClearTemporaryLocation", resourceCulture);
            }
        }
        
        public static string ClearDehydratedLocation {
            get {
                return ResourceManager.GetString("ClearDehydratedLocation", resourceCulture);
            }
        }
        
        public static string ClearFolder {
            get {
                return ResourceManager.GetString("ClearFolder", resourceCulture);
            }
        }
        
        public static string DevBuildsCachePathDisplay {
            get {
                return ResourceManager.GetString("DevBuildsCachePathDisplay", resourceCulture);
            }
        }
        
        public static string SelectDevBuildCacheLocation {
            get {
                return ResourceManager.GetString("SelectDevBuildCacheLocation", resourceCulture);
            }
        }
        
        public static string ResetCacheLocation {
            get {
                return ResourceManager.GetString("ResetCacheLocation", resourceCulture);
            }
        }
        
        public static string CacheSizeDisplay {
            get {
                return ResourceManager.GetString("CacheSizeDisplay", resourceCulture);
            }
        }
        
        public static string DevCenterConnectionDialogTitle {
            get {
                return ResourceManager.GetString("DevCenterConnectionDialogTitle", resourceCulture);
            }
        }
        
        public static string DialogOk {
            get {
                return ResourceManager.GetString("DialogOk", resourceCulture);
            }
        }
        
        public static string ConnectionInfoTab {
            get {
                return ResourceManager.GetString("ConnectionInfoTab", resourceCulture);
            }
        }
        
        public static string ConnectedAsUserDisplay {
            get {
                return ResourceManager.GetString("ConnectedAsUserDisplay", resourceCulture);
            }
        }
        
        public static string YouAreDeveloperInfo {
            get {
                return ResourceManager.GetString("YouAreDeveloperInfo", resourceCulture);
            }
        }
        
        public static string YouAreASupporter {
            get {
                return ResourceManager.GetString("YouAreASupporter", resourceCulture);
            }
        }
        
        public static string BuildTypeSelectionBOTD {
            get {
                return ResourceManager.GetString("BuildTypeSelectionBOTD", resourceCulture);
            }
        }
        
        public static string BuildTypeSelectionLatest {
            get {
                return ResourceManager.GetString("BuildTypeSelectionLatest", resourceCulture);
            }
        }
        
        public static string BuildTypeSelectionManual {
            get {
                return ResourceManager.GetString("BuildTypeSelectionManual", resourceCulture);
            }
        }
        
        public static string LogoutButton {
            get {
                return ResourceManager.GetString("LogoutButton", resourceCulture);
            }
        }
        
        public static string DevCenterConnectionExplanation {
            get {
                return ResourceManager.GetString("DevCenterConnectionExplanation", resourceCulture);
            }
        }
        
        public static string ConnectionInstructionsWikiPrompt {
            get {
                return ResourceManager.GetString("ConnectionInstructionsWikiPrompt", resourceCulture);
            }
        }
        
        public static string ConnectionInstructionsGetLinkCode {
            get {
                return ResourceManager.GetString("ConnectionInstructionsGetLinkCode", resourceCulture);
            }
        }
        
        public static string ConnectionKeyPlaceholder {
            get {
                return ResourceManager.GetString("ConnectionKeyPlaceholder", resourceCulture);
            }
        }
        
        public static string ConnectButton {
            get {
                return ResourceManager.GetString("ConnectButton", resourceCulture);
            }
        }
        
        public static string LoginButton {
            get {
                return ResourceManager.GetString("LoginButton", resourceCulture);
            }
        }
        
        public static string ConfirmButton {
            get {
                return ResourceManager.GetString("ConfirmButton", resourceCulture);
            }
        }
        
        public static string SpecificBuildTab {
            get {
                return ResourceManager.GetString("SpecificBuildTab", resourceCulture);
            }
        }
        
        public static string ManuallyEnteredHashDisplay {
            get {
                return ResourceManager.GetString("ManuallyEnteredHashDisplay", resourceCulture);
            }
        }
        
        public static string EnterBuildHashPlaceholder {
            get {
                return ResourceManager.GetString("EnterBuildHashPlaceholder", resourceCulture);
            }
        }
        
        public static string SelectButton {
            get {
                return ResourceManager.GetString("SelectButton", resourceCulture);
            }
        }
        
        public static string ManualHashSelectButtonToolTip {
            get {
                return ResourceManager.GetString("ManualHashSelectButtonToolTip", resourceCulture);
            }
        }
        
        public static string FetchLatestBuildsButton {
            get {
                return ResourceManager.GetString("FetchLatestBuildsButton", resourceCulture);
            }
        }
        
        public static string SettingsSaveFailedTitle {
            get {
                return ResourceManager.GetString("SettingsSaveFailedTitle", resourceCulture);
            }
        }
        
        public static string SettingsSaveFailedMessage {
            get {
                return ResourceManager.GetString("SettingsSaveFailedMessage", resourceCulture);
            }
        }
        
        public static string SizeInMiB {
            get {
                return ResourceManager.GetString("SizeInMiB", resourceCulture);
            }
        }
        
        public static string InstalledFolderSize {
            get {
                return ResourceManager.GetString("InstalledFolderSize", resourceCulture);
            }
        }
        
        public static string FolderNotFound {
            get {
                return ResourceManager.GetString("FolderNotFound", resourceCulture);
            }
        }
        
        public static string ThriveInstallFolderNotFound {
            get {
                return ResourceManager.GetString("ThriveInstallFolderNotFound", resourceCulture);
            }
        }
        
        public static string LauncherSourceCodeButton {
            get {
                return ResourceManager.GetString("LauncherSourceCodeButton", resourceCulture);
            }
        }
        
        public static string ViewLicensesButton {
            get {
                return ResourceManager.GetString("ViewLicensesButton", resourceCulture);
            }
        }
        
        public static string MainWindowTitle {
            get {
                return ResourceManager.GetString("MainWindowTitle", resourceCulture);
            }
        }
        
        public static string LicensesWindowTitle {
            get {
                return ResourceManager.GetString("LicensesWindowTitle", resourceCulture);
            }
        }
        
        public static string RobotoLicenseTitle {
            get {
                return ResourceManager.GetString("RobotoLicenseTitle", resourceCulture);
            }
        }
        
        public static string LatoLicenseTitle {
            get {
                return ResourceManager.GetString("LatoLicenseTitle", resourceCulture);
            }
        }
        
        public static string FeedFetchError {
            get {
                return ResourceManager.GetString("FeedFetchError", resourceCulture);
            }
        }
        
        public static string FeedItemPostedByAndTime {
            get {
                return ResourceManager.GetString("FeedItemPostedByAndTime", resourceCulture);
            }
        }
        
        public static string ClickHereLink {
            get {
                return ResourceManager.GetString("ClickHereLink", resourceCulture);
            }
        }
        
        public static string TruncatedClickSuffix {
            get {
                return ResourceManager.GetString("TruncatedClickSuffix", resourceCulture);
            }
        }
        
        public static string LogFolderCreateFailed {
            get {
                return ResourceManager.GetString("LogFolderCreateFailed", resourceCulture);
            }
        }
        
        public static string OpenLogsFolderButton {
            get {
                return ResourceManager.GetString("OpenLogsFolderButton", resourceCulture);
            }
        }
        
        public static string AllSigningKeysExpiredTitle {
            get {
                return ResourceManager.GetString("AllSigningKeysExpiredTitle", resourceCulture);
            }
        }
        
        public static string AllSigningKeysExpired {
            get {
                return ResourceManager.GetString("AllSigningKeysExpired", resourceCulture);
            }
        }
        
        public static string StoreVersionName {
            get {
                return ResourceManager.GetString("StoreVersionName", resourceCulture);
            }
        }
        
        public static string VersionWithPlatform {
            get {
                return ResourceManager.GetString("VersionWithPlatform", resourceCulture);
            }
        }
        
        public static string LoadingDotDotDot {
            get {
                return ResourceManager.GetString("LoadingDotDotDot", resourceCulture);
            }
        }
        
        public static string VersionInfoLoadFailureTitle {
            get {
                return ResourceManager.GetString("VersionInfoLoadFailureTitle", resourceCulture);
            }
        }
        
        public static string VersionInfoLoadFailureExplanation {
            get {
                return ResourceManager.GetString("VersionInfoLoadFailureExplanation", resourceCulture);
            }
        }
        
        public static string VersionInfoLoadFailureBadData {
            get {
                return ResourceManager.GetString("VersionInfoLoadFailureBadData", resourceCulture);
            }
        }
        
        public static string Retry {
            get {
                return ResourceManager.GetString("Retry", resourceCulture);
            }
        }
        
        public static string UseCached {
            get {
                return ResourceManager.GetString("UseCached", resourceCulture);
            }
        }
        
        public static string UnknownError {
            get {
                return ResourceManager.GetString("UnknownError", resourceCulture);
            }
        }
        
        public static string NoCompatibleVersionsFoundTitle {
            get {
                return ResourceManager.GetString("NoCompatibleVersionsFoundTitle", resourceCulture);
            }
        }
        
        public static string NoCompatibleVersionsFound {
            get {
                return ResourceManager.GetString("NoCompatibleVersionsFound", resourceCulture);
            }
        }
        
        public static string LatestVersionTag {
            get {
                return ResourceManager.GetString("LatestVersionTag", resourceCulture);
            }
        }
        
        public static string MoveVersionsTitle {
            get {
                return ResourceManager.GetString("MoveVersionsTitle", resourceCulture);
            }
        }
        
        public static string MoveVersionsExplanation {
            get {
                return ResourceManager.GetString("MoveVersionsExplanation", resourceCulture);
            }
        }
        
        public static string MoveFilesTitle {
            get {
                return ResourceManager.GetString("MoveFilesTitle", resourceCulture);
            }
        }
        
        public static string MoveDehydratedCacheExplanation {
            get {
                return ResourceManager.GetString("MoveDehydratedCacheExplanation", resourceCulture);
            }
        }
        
        public static string InternalErrorTitle {
            get {
                return ResourceManager.GetString("InternalErrorTitle", resourceCulture);
            }
        }
        
        public static string InternalErrorExplanation {
            get {
                return ResourceManager.GetString("InternalErrorExplanation", resourceCulture);
            }
        }
        
        public static string Move {
            get {
                return ResourceManager.GetString("Move", resourceCulture);
            }
        }
        
        public static string Skip {
            get {
                return ResourceManager.GetString("Skip", resourceCulture);
            }
        }
        
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        public static string DeleteErrorTitle {
            get {
                return ResourceManager.GetString("DeleteErrorTitle", resourceCulture);
            }
        }
        
        public static string DeleteErrorExplanation {
            get {
                return ResourceManager.GetString("DeleteErrorExplanation", resourceCulture);
            }
        }
        
        public static string DeleteErrorDoesNotExist {
            get {
                return ResourceManager.GetString("DeleteErrorDoesNotExist", resourceCulture);
            }
        }
        
        public static string UnknownFolder {
            get {
                return ResourceManager.GetString("UnknownFolder", resourceCulture);
            }
        }
        
        public static string ClearTemporaryFilesPromptTitle {
            get {
                return ResourceManager.GetString("ClearTemporaryFilesPromptTitle", resourceCulture);
            }
        }
        
        public static string ClearTemporaryFilesPromptExplanation {
            get {
                return ResourceManager.GetString("ClearTemporaryFilesPromptExplanation", resourceCulture);
            }
        }
        
        public static string ClearTemporaryFilesCount {
            get {
                return ResourceManager.GetString("ClearTemporaryFilesCount", resourceCulture);
            }
        }
        
        public static string ClearDehydratedFilesPromptTitle {
            get {
                return ResourceManager.GetString("ClearDehydratedFilesPromptTitle", resourceCulture);
            }
        }
        
        public static string ClearDehydratedFilesPromptExplanation {
            get {
                return ResourceManager.GetString("ClearDehydratedFilesPromptExplanation", resourceCulture);
            }
        }
        
        public static string ClearDehydratedFilesCount {
            get {
                return ResourceManager.GetString("ClearDehydratedFilesCount", resourceCulture);
            }
        }
        
        public static string ErrorSuggestionForMissingDll {
            get {
                return ResourceManager.GetString("ErrorSuggestionForMissingDll", resourceCulture);
            }
        }
        
        public static string ErrorSuggestionForStartupFailure {
            get {
                return ResourceManager.GetString("ErrorSuggestionForStartupFailure", resourceCulture);
            }
        }
        
        public static string LauncherIsLatestVersion {
            get {
                return ResourceManager.GetString("LauncherIsLatestVersion", resourceCulture);
            }
        }
        
        public static string OutdatedLauncherVersionComparison {
            get {
                return ResourceManager.GetString("OutdatedLauncherVersionComparison", resourceCulture);
            }
        }
        
        public static string LauncherDownloadsPageButton {
            get {
                return ResourceManager.GetString("LauncherDownloadsPageButton", resourceCulture);
            }
        }
        
        public static string OutdatedLauncherTitle {
            get {
                return ResourceManager.GetString("OutdatedLauncherTitle", resourceCulture);
            }
        }
        
        public static string OutdatedLauncherExplanation {
            get {
                return ResourceManager.GetString("OutdatedLauncherExplanation", resourceCulture);
            }
        }
        
        public static string DevCenterConnectFailureTitle {
            get {
                return ResourceManager.GetString("DevCenterConnectFailureTitle", resourceCulture);
            }
        }
        
        public static string DevCenterConnectFailureForbidden {
            get {
                return ResourceManager.GetString("DevCenterConnectFailureForbidden", resourceCulture);
            }
        }
        
        public static string DevCenterConnectFailureConnection {
            get {
                return ResourceManager.GetString("DevCenterConnectFailureConnection", resourceCulture);
            }
        }
        
        public static string DevCenterConnectFailureUnknown {
            get {
                return ResourceManager.GetString("DevCenterConnectFailureUnknown", resourceCulture);
            }
        }
        
        public static string DisconnectDevCenter {
            get {
                return ResourceManager.GetString("DisconnectDevCenter", resourceCulture);
            }
        }
        
        public static string CheckDevCenterTokensLink {
            get {
                return ResourceManager.GetString("CheckDevCenterTokensLink", resourceCulture);
            }
        }
        
        public static string RetryExistingConnection {
            get {
                return ResourceManager.GetString("RetryExistingConnection", resourceCulture);
            }
        }
        
        public static string EnterDevCenterConnectionCode {
            get {
                return ResourceManager.GetString("EnterDevCenterConnectionCode", resourceCulture);
            }
        }
        
        public static string DevCenterConnectAttemptError {
            get {
                return ResourceManager.GetString("DevCenterConnectAttemptError", resourceCulture);
            }
        }
        
        public static string ConfirmValidLink {
            get {
                return ResourceManager.GetString("ConfirmValidLink", resourceCulture);
            }
        }
        
        public static string NewLinkUsername {
            get {
                return ResourceManager.GetString("NewLinkUsername", resourceCulture);
            }
        }
        
        public static string NewLinkEmail {
            get {
                return ResourceManager.GetString("NewLinkEmail", resourceCulture);
            }
        }
        
        public static string LinkFormingFailedError {
            get {
                return ResourceManager.GetString("LinkFormingFailedError", resourceCulture);
            }
        }
        
        public static string LoginToSeeThisContent {
            get {
                return ResourceManager.GetString("LoginToSeeThisContent", resourceCulture);
            }
        }
        
        public static string UnsafeBuild {
            get {
                return ResourceManager.GetString("UnsafeBuild", resourceCulture);
            }
        }
        
        public static string BuildOfTheDayAbbreviation {
            get {
                return ResourceManager.GetString("BuildOfTheDayAbbreviation", resourceCulture);
            }
        }
        
        public static string BuildDescriptionLabelShort {
            get {
                return ResourceManager.GetString("BuildDescriptionLabelShort", resourceCulture);
            }
        }
        
        public static string CannotPlayThriveTitle {
            get {
                return ResourceManager.GetString("CannotPlayThriveTitle", resourceCulture);
            }
        }
        
        public static string ThriveCurrentlyRunning {
            get {
                return ResourceManager.GetString("ThriveCurrentlyRunning", resourceCulture);
            }
        }
        
        public static string NoVersionSelected {
            get {
                return ResourceManager.GetString("NoVersionSelected", resourceCulture);
            }
        }
        
        public static string PlayingTitle {
            get {
                return ResourceManager.GetString("PlayingTitle", resourceCulture);
            }
        }
        
        public static string GettingDevBuildInfoMessage {
            get {
                return ResourceManager.GetString("GettingDevBuildInfoMessage", resourceCulture);
            }
        }
        
        public static string ErrorGettingDevBuild {
            get {
                return ResourceManager.GetString("ErrorGettingDevBuild", resourceCulture);
            }
        }
        
        public static string ThriveRunCanceled {
            get {
                return ResourceManager.GetString("ThriveRunCanceled", resourceCulture);
            }
        }
        
        public static string PlayingUnsafeBuildWasCanceled {
            get {
                return ResourceManager.GetString("PlayingUnsafeBuildWasCanceled", resourceCulture);
            }
        }
        
        public static string ThriveRunError {
            get {
                return ResourceManager.GetString("ThriveRunError", resourceCulture);
            }
        }
        
        public static string CloseButton {
            get {
                return ResourceManager.GetString("CloseButton", resourceCulture);
            }
        }
        
        public static string NoBuildToPlayFound {
            get {
                return ResourceManager.GetString("NoBuildToPlayFound", resourceCulture);
            }
        }
        
        public static string DownloadingItem {
            get {
                return ResourceManager.GetString("DownloadingItem", resourceCulture);
            }
        }
        
        public static string DownloadError {
            get {
                return ResourceManager.GetString("DownloadError", resourceCulture);
            }
        }
        
        public static string ExtractError {
            get {
                return ResourceManager.GetString("ExtractError", resourceCulture);
            }
        }
        
        public static string MissingThriveFolderError {
            get {
                return ResourceManager.GetString("MissingThriveFolderError", resourceCulture);
            }
        }
        
        public static string MissingThriveExecutableError {
            get {
                return ResourceManager.GetString("MissingThriveExecutableError", resourceCulture);
            }
        }
        
        public static string VersionInstallationOrCheckFailed {
            get {
                return ResourceManager.GetString("VersionInstallationOrCheckFailed", resourceCulture);
            }
        }
        
        public static string ThriveFolderPrepareFailed {
            get {
                return ResourceManager.GetString("ThriveFolderPrepareFailed", resourceCulture);
            }
        }
        
        public static string DownloadProgressDisplay {
            get {
                return ResourceManager.GetString("DownloadProgressDisplay", resourceCulture);
            }
        }
        
        public static string ItemProgressDisplay {
            get {
                return ResourceManager.GetString("ItemProgressDisplay", resourceCulture);
            }
        }
        
        public static string UnknownNumber {
            get {
                return ResourceManager.GetString("UnknownNumber", resourceCulture);
            }
        }
        
        public static string DownloadingStateItemProgress {
            get {
                return ResourceManager.GetString("DownloadingStateItemProgress", resourceCulture);
            }
        }
        
        public static string VerifyingStateItemProgress {
            get {
                return ResourceManager.GetString("VerifyingStateItemProgress", resourceCulture);
            }
        }
        
        public static string ExtractingStateItemProgress {
            get {
                return ResourceManager.GetString("ExtractingStateItemProgress", resourceCulture);
            }
        }
        
        public static string ProcessingStateItemProgress {
            get {
                return ResourceManager.GetString("ProcessingStateItemProgress", resourceCulture);
            }
        }
        
        public static string ThriveLaunchFailurePreventedAutoClose {
            get {
                return ResourceManager.GetString("ThriveLaunchFailurePreventedAutoClose", resourceCulture);
            }
        }
        
        public static string TruncatedGameOutputWarning {
            get {
                return ResourceManager.GetString("TruncatedGameOutputWarning", resourceCulture);
            }
        }
        
        public static string ThriveIsStarting {
            get {
                return ResourceManager.GetString("ThriveIsStarting", resourceCulture);
            }
        }
        
        public static string ReportCrashButton {
            get {
                return ResourceManager.GetString("ReportCrashButton", resourceCulture);
            }
        }
        
        public static string ExtraThriveStartFlags {
            get {
                return ResourceManager.GetString("ExtraThriveStartFlags", resourceCulture);
            }
        }
        
        public static string StoreVersionExternalVersionsNote {
            get {
                return ResourceManager.GetString("StoreVersionExternalVersionsNote", resourceCulture);
            }
        }
        
        public static string DevBuildTypeSelectionHeading {
            get {
                return ResourceManager.GetString("DevBuildTypeSelectionHeading", resourceCulture);
            }
        }
        
        public static string PlayUnsafeBuildTitle {
            get {
                return ResourceManager.GetString("PlayUnsafeBuildTitle", resourceCulture);
            }
        }
        
        public static string PlayUnsafeBuildExplanation {
            get {
                return ResourceManager.GetString("PlayUnsafeBuildExplanation", resourceCulture);
            }
        }
        
        public static string AcceptUnsafeBuildButton {
            get {
                return ResourceManager.GetString("AcceptUnsafeBuildButton", resourceCulture);
            }
        }
        
        public static string FoundDevBuildToPlayInfo {
            get {
                return ResourceManager.GetString("FoundDevBuildToPlayInfo", resourceCulture);
            }
        }
        
        public static string FoundDevBuildToPlayDescription {
            get {
                return ResourceManager.GetString("FoundDevBuildToPlayDescription", resourceCulture);
            }
        }
        
        public static string RehydrationFailed {
            get {
                return ResourceManager.GetString("RehydrationFailed", resourceCulture);
            }
        }
        
        public static string RehydrationStarting {
            get {
                return ResourceManager.GetString("RehydrationStarting", resourceCulture);
            }
        }
        
        public static string CopyLogWindowToClipboardToolTip {
            get {
                return ResourceManager.GetString("CopyLogWindowToClipboardToolTip", resourceCulture);
            }
        }
        
        public static string CrashReporterWindowTitle {
            get {
                return ResourceManager.GetString("CrashReporterWindowTitle", resourceCulture);
            }
        }
        
        public static string ContinueReportingButton {
            get {
                return ResourceManager.GetString("ContinueReportingButton", resourceCulture);
            }
        }
        
        public static string CancelCreatingReportTitle {
            get {
                return ResourceManager.GetString("CancelCreatingReportTitle", resourceCulture);
            }
        }
        
        public static string CancelCreatingReportExplanation {
            get {
                return ResourceManager.GetString("CancelCreatingReportExplanation", resourceCulture);
            }
        }
        
        public static string ClearAllCrashesButton {
            get {
                return ResourceManager.GetString("ClearAllCrashesButton", resourceCulture);
            }
        }
        
        public static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        public static string SubmittingReportMessage {
            get {
                return ResourceManager.GetString("SubmittingReportMessage", resourceCulture);
            }
        }
        
        public static string ErrorSubmittingReport {
            get {
                return ResourceManager.GetString("ErrorSubmittingReport", resourceCulture);
            }
        }
        
        public static string SubmittingReportExtraInfo {
            get {
                return ResourceManager.GetString("SubmittingReportExtraInfo", resourceCulture);
            }
        }
        
        public static string SubmitRetryButton {
            get {
                return ResourceManager.GetString("SubmitRetryButton", resourceCulture);
            }
        }
        
        public static string SuccessfulReportSubmitMessage {
            get {
                return ResourceManager.GetString("SuccessfulReportSubmitMessage", resourceCulture);
            }
        }
        
        public static string ReportViewingPublicInfo {
            get {
                return ResourceManager.GetString("ReportViewingPublicInfo", resourceCulture);
            }
        }
        
        public static string ReportDeleteInfo {
            get {
                return ResourceManager.GetString("ReportDeleteInfo", resourceCulture);
            }
        }
        
        public static string ReportDeleteCaveat {
            get {
                return ResourceManager.GetString("ReportDeleteCaveat", resourceCulture);
            }
        }
        
        public static string ReporterEndMessage {
            get {
                return ResourceManager.GetString("ReporterEndMessage", resourceCulture);
            }
        }
        
        public static string SecondsDisplayPlural {
            get {
                return ResourceManager.GetString("SecondsDisplayPlural", resourceCulture);
            }
        }
        
        public static string SecondsDisplaySingular {
            get {
                return ResourceManager.GetString("SecondsDisplaySingular", resourceCulture);
            }
        }
        
        public static string StopAutoClose {
            get {
                return ResourceManager.GetString("StopAutoClose", resourceCulture);
            }
        }
        
        public static string AutoCloseStopped {
            get {
                return ResourceManager.GetString("AutoCloseStopped", resourceCulture);
            }
        }
        
        public static string CopyToClipboard {
            get {
                return ResourceManager.GetString("CopyToClipboard", resourceCulture);
            }
        }
        
        public static string TimeMomentRightNow {
            get {
                return ResourceManager.GetString("TimeMomentRightNow", resourceCulture);
            }
        }
        
        public static string AtTime {
            get {
                return ResourceManager.GetString("AtTime", resourceCulture);
            }
        }
        
        public static string ViewFile {
            get {
                return ResourceManager.GetString("ViewFile", resourceCulture);
            }
        }
        
        public static string OpenFolder {
            get {
                return ResourceManager.GetString("OpenFolder", resourceCulture);
            }
        }
        
        public static string IncludeInReport {
            get {
                return ResourceManager.GetString("IncludeInReport", resourceCulture);
            }
        }
        
        public static string ActiveReportingInfo {
            get {
                return ResourceManager.GetString("ActiveReportingInfo", resourceCulture);
            }
        }
        
        public static string CrashReportLogsSection {
            get {
                return ResourceManager.GetString("CrashReportLogsSection", resourceCulture);
            }
        }
        
        public static string CrashReportLogsSectionExplanation {
            get {
                return ResourceManager.GetString("CrashReportLogsSectionExplanation", resourceCulture);
            }
        }
        
        public static string CrashReportDescriptionField {
            get {
                return ResourceManager.GetString("CrashReportDescriptionField", resourceCulture);
            }
        }
        
        public static string CrashReportDescriptionFieldPlaceholder {
            get {
                return ResourceManager.GetString("CrashReportDescriptionFieldPlaceholder", resourceCulture);
            }
        }
        
        public static string CrashReportEmailField {
            get {
                return ResourceManager.GetString("CrashReportEmailField", resourceCulture);
            }
        }
        
        public static string CrashReportEmailFieldPlaceholder {
            get {
                return ResourceManager.GetString("CrashReportEmailFieldPlaceholder", resourceCulture);
            }
        }
        
        public static string CrashReportEmailFieldNotice {
            get {
                return ResourceManager.GetString("CrashReportEmailFieldNotice", resourceCulture);
            }
        }
        
        public static string CrashReportIsPublic {
            get {
                return ResourceManager.GetString("CrashReportIsPublic", resourceCulture);
            }
        }
        
        public static string CrashReportSubmitAcceptConfirmation {
            get {
                return ResourceManager.GetString("CrashReportSubmitAcceptConfirmation", resourceCulture);
            }
        }
        
        public static string SelectCrashToReport {
            get {
                return ResourceManager.GetString("SelectCrashToReport", resourceCulture);
            }
        }
        
        public static string CrashReportDeleteAfterSubmitting {
            get {
                return ResourceManager.GetString("CrashReportDeleteAfterSubmitting", resourceCulture);
            }
        }
    }
}
